### PR TITLE
Improve README of the 'http' promise type module

### PR DESCRIPTION
**Pull request by vpodzime**
Ticket: ENT-7624

### CODE REVIEW

**Review by olehermanse — CHANGES_REQUESTED** [review]
Please remove the README.md that I added, and use the same format as the other promise types to make it a little more consistent:

https://github.com/cfengine/modules/blob/master/promise-types/git/README.md

**Comment by vpodzime** [comment]
> use the same format as the other promise types to make it a little more consistent

I don't like the attributes table, especially when attributes here can have multiple various types.

**Comment by olehermanse** [comment]
> I don't like the attributes table, especially when attributes here can have multiple various types.

As a user I like the information it provides, and also seeing somewhat consistent information across promise types is nice.

**Comment by vpodzime** [comment]
> also seeing somewhat consistent information across promise types is nice.

Then we should come up with a better format and make it consistent across the modules.

**Review by olehermanse — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
